// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Application {
  port: number;
  directory: string;
  binary: string;
  name: string;
  color: string;
  args: Array<string>;
}
